### ISSUE TITLE
Request: Publish to Pursuit

### ISSUE THREAD

**Issue by fosskers** [eskimor/purescript-servant-support#13]
For nice, rendered docs :)

**Comment by eskimor** [comment]
Hmm. I mean it would not harm, but this library is not actually intended to be used directly, but rather by auto generated code from servant-purescript.

**Comment by fosskers** [comment]
And unfortunately I can't remember the original reason why I wanted to look at the rendered docs in the first place. Probably to figure [this stuff](https://github.com/fosskers/fosskers.ca/blob/master/site/src/Types.purs#L93) out.

**Comment by eskimor** [comment]
yeah sorry - that issue got lost somehow.
